
class wynik():
    def srednia(self,ilosc_probek,lista_1,lista_2,lista_3,lista_4,lista_5,lista_6,lista_7,lista_8,lista_9,lista_10,lista_11,lista_12,lista_13,lista_14,
                lista_15,lista_16,lista_17,lista_18,lista_19,lista_20,lista_21,lista_22,lista_23,lista_24,lista_25,lista_26,lista_27,lista_28):
        if ilosc_probek > 2048 or ilosc_probek < 2048:
            print("Róźnica1 RMS               : ", lista_1)
            print("Róźnica2 min amp           : ", lista_2)
            print("Róźnica3 f min amp         : ", lista_3)
            print("Róźnica4 f amx amp         : ", lista_4)
            print("Róźnica5 suma              : ", lista_5)
            print("Róźnica6 f roll off        : ", lista_6)
            print("Róźnica7 amp roll off      : ", lista_7)
            print("Róźnica8 zer crosssing     : ", lista_8)
            print("Róźnica9 amp spektrogram   : ", lista_9)
            print("Róźnica10 centroid         : ", lista_10)
            print("Róźnica11 centroid roll off: ", lista_11)
            print("Róźnica12 Euklides dis 1   : ", lista_12)
            print("Róźnica13 Euklides dis 2   : ", lista_13)
            print("Róźnica14 Dynamic          : ", lista_14)
            print("Róźnica15 Dynamic roll off : ", lista_15)
            print("Róźnica16 MFCC 1           : ", lista_16)
            print("Róźnica17 MFCC 2           : ", lista_17)
            print("Róźnica18 MFCC 3           : ", lista_18)
            print("Róźnica19 MFCC 4           : ", lista_19)
            print("Róźnica20 MFCC 5           : ", lista_20)
            print("Róźnica21 MFCC 6           : ", lista_21)
            print("Róźnica22 MFCC 7           : ", lista_22)
            print("Róźnica23 MFCC 8           : ", lista_23)
            print("Róźnica24 MFCC 9           : ", lista_24)
            print("Róźnica25 MFCC 10          : ", lista_25)
            print("Róźnica26 MFCC 11          : ", lista_26)
            print("Róźnica27 MFCC 12          : ", lista_27)
            print("Róźnica28 MFCC 13          : ", lista_28)


            srednia_1 = sum(lista_1) / (len(lista_1))
            srednia_2 = sum(lista_2) / (len(lista_2))
            srednia_3 = sum(lista_3) / (len(lista_3))
            srednia_4 = sum(lista_4) / (len(lista_4))
            srednia_5 = sum(lista_5) / (len(lista_5))
            srednia_6 = sum(lista_6) / (len(lista_6))
            srednia_7 = sum(lista_7) / (len(lista_7))
            srednia_8 = sum(lista_8) / (len(lista_8))
            srednia_9 = sum(lista_9) / (len(lista_9))
            srednia_10 = sum(lista_10) / (len(lista_10))
            srednia_11 = sum(lista_11) / (len(lista_11))
            srednia_12 = sum(lista_12) / (len(lista_12))
            srednia_13 = sum(lista_13) / (len(lista_13))
            srednia_14 = sum(lista_14) / (len(lista_14))
            srednia_15 = sum(lista_15) / (len(lista_15))
            srednia_16 = sum(lista_16) / (len(lista_16))
            srednia_17 = sum(lista_17) / (len(lista_17))
            srednia_18 = sum(lista_18) / (len(lista_18))
            srednia_19 = sum(lista_19) / (len(lista_19))
            srednia_20 = sum(lista_20) / (len(lista_20))
            srednia_21 = sum(lista_21) / (len(lista_21))
            srednia_22 = sum(lista_22) / (len(lista_22))
            srednia_23 = sum(lista_23) / (len(lista_23))
            srednia_24 = sum(lista_24) / (len(lista_24))
            srednia_25 = sum(lista_25) / (len(lista_25))
            srednia_26 = sum(lista_26) / (len(lista_26))
            srednia_27 = sum(lista_27) / (len(lista_27))
            srednia_28 = sum(lista_28) / (len(lista_28))


            print("Róźnica1 RMS               : ", srednia_1)
            print("Róźnica2 min amp           : ", srednia_2)
            print("Róźnica3 f min amp         : ", srednia_3)
            print("Róźnica4 f amx amp         : ", srednia_4)
            print("Róźnica5 suma              : ", srednia_5)
            print("Róźnica6 f roll off        : ", srednia_6)
            print("Róźnica7 amp roll off      : ", srednia_7)
            print("Róźnica8 zer crosssing     : ", srednia_8)
            print("Róźnica9 amp spektrogram   : ", srednia_9)
            print("Róźnica10 centroid         : ", srednia_10)
            print("Róźnica11 centroid roll off: ", srednia_11)
            print("Róźnica12 Euklides dis 1   : ", srednia_12)
            print("Róźnica13 Euklides dis 2   : ", srednia_13)
            print("Róźnica14 Dynamic          : ", srednia_14)
            print("Róźnica15 Dynamic roll off : ", srednia_15)
            print("Róźnica16 MFCC             : ", srednia_16)
            print("Róźnica17 MFCC             : ", srednia_17)
            print("Róźnica18 MFCC             : ", srednia_18)
            print("Róźnica19 MFCC             : ", srednia_19)
            print("Róźnica20 MFCC             : ", srednia_20)
            print("Róźnica21 MFCC             : ", srednia_21)
            print("Róźnica22 MFCC             : ", srednia_22)
            print("Róźnica23 MFCC             : ", srednia_23)
            print("Róźnica24 MFCC             : ", srednia_24)
            print("Róźnica25 MFCC             : ", srednia_25)
            print("Róźnica26 MFCC             : ", srednia_26)
            print("Róźnica27 MFCC             : ", srednia_27)
            print("Róźnica28 MFCC             : ", srednia_28)

            lista_suma = [srednia_1, srednia_2, srednia_4, srednia_5, srednia_6, srednia_7,srednia_8, srednia_9,srednia_10,srednia_11, srednia_12,srednia_13,srednia_14,srednia_15,
                          srednia_16,srednia_17]

            print("Sygnał różni się o:", round(sum(lista_suma) / len(lista_suma),2),"%")

